name: wise_converter
description: Converter utils for Wise.
version: 0.1.0

publish_to: 'none'

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  args: ^2.0.0
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  wise_toolkit:
    path: ./packages/wise_toolkit/
  xml: ^6.0.1

dev_dependencies:
  http: ^0.13.0
  lints: ^1.0.0
  test_process: ^2.0.0
  test: ^1.15.0
