name: wise_toolkit
description: Toolkit for work with Wise.
version: 0.1.0

publish_to: 'none'

environment:
  sdk: '>=3.0.0'

dependencies: 
  list_ext: ^1.0.6
  
dev_dependencies:
  flutter_lints: ^2.0.0
  test: ^1.24.6
  tuple: ^2.0.2
